// Auto-generated by scripts/generate-middleware.mjs — do not edit manually
const STATIC_ROUTE_MAP = {
  "/": "/static-seo/index.html",
  "/request-quote": "/static-seo/request-quote.html",
  "/iraq-bullion-quote": "/static-seo/iraq-bullion-quote.html",
  "/gold-bars": "/static-seo/gold-bars.html",
  "/silver-bars": "/static-seo/silver-bars.html",
  "/bullion-coins": "/static-seo/bullion-coins.html",
  "/custom-inquiry": "/static-seo/custom-inquiry.html",
  "/allocated-storage": "/static-seo/allocated-storage.html",
  "/sell-back": "/static-seo/sell-back.html",
  "/faq": "/static-seo/faq.html",
  "/contact": "/static-seo/contact.html",
  "/compliance": "/static-seo/compliance.html",
  "/terms": "/static-seo/terms.html",
  "/privacy-policy": "/static-seo/privacy-policy.html",
  "/kyc-aml-policy": "/static-seo/kyc-aml-policy.html",
  "/pricing-disclaimer": "/static-seo/pricing-disclaimer.html",
  "/refund-cancellation-policy": "/static-seo/refund-cancellation-policy.html",
  "/delivery-collection-policy": "/static-seo/delivery-collection-policy.html",
  "/risk-disclosure": "/static-seo/risk-disclosure.html",
  "/cookie-policy": "/static-seo/cookie-policy.html",
  "/allocated-storage-terms": "/static-seo/allocated-storage-terms.html",
  "/sell-back-policy": "/static-seo/sell-back-policy.html",
  "/buy-gold-bars-dubai": "/static-seo/buy-gold-bars-dubai.html",
  "/buy-silver-bars-dubai": "/static-seo/buy-silver-bars-dubai.html",
  "/gold-rate-dubai-today": "/static-seo/gold-rate-dubai-today.html",
  "/silver-rate-dubai-today": "/static-seo/silver-rate-dubai-today.html",
  "/sell-gold-dubai": "/static-seo/sell-gold-dubai.html",
  "/bullion-desk-dubai": "/static-seo/bullion-desk-dubai.html",
  "/allocated-storage-dubai": "/static-seo/allocated-storage-dubai.html",
  "/24k-gold-bars-uae": "/static-seo/24k-gold-bars-uae.html",
  "/silver-bars-iraq": "/static-seo/silver-bars-iraq.html",
  "/sam-palm-silver-iraq": "/static-seo/sam-palm-silver-iraq.html",
  "/gold-bars-baghdad": "/static-seo/gold-bars-baghdad.html",
  "/silver-bars-erbil": "/static-seo/silver-bars-erbil.html",
  "/bullion-desk-iraq": "/static-seo/bullion-desk-iraq.html"
};

const BOT_RE =
  /googlebot|bingbot|baiduspider|yandex|duckduckbot|slurp|facebookexternalhit|twitterbot|linkedinbot|slackbot|discordbot|whatsapp|telegrambot|applebot|semrushbot|ahrefsbot|mj12bot|petalbot/i;

export const config = {
  matcher: [
    "/((?!api/|images/|assets/|videos/|brand/|static-seo/|robots\\.txt|sitemap\\.xml|manifest\\.json|favicon\\.ico|_next/).*)"
  ]
};

export default async function middleware(request) {
  const ua = request.headers.get("user-agent") || "";
  if (!BOT_RE.test(ua)) return;

  const { pathname } = new URL(request.url);
  const staticPath = STATIC_ROUTE_MAP[pathname];
  if (!staticPath) return;

  const target = new URL(staticPath, request.url);
  const response = await fetch(target.toString());
  return new Response(response.body, {
    status: response.status,
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "public, max-age=3600"
    }
  });
}
