/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Product } from "./types";

export const BRANDS = [
  { name: "PAMP Suisse", origin: "Switzerland", description: "World-leading bullion brand renowned for artistic craftsmanship and security certificates." },
  { name: "Valcambi", origin: "Switzerland", description: "One of the oldest and largest Swiss precious metal refineries, known for high-purity castings." },
  { name: "Emirates Gold", origin: "United Arab Emirates", description: "The premier gold refinery in the UAE with recognized international accreditation." },
  { name: "SAM Precious Metals", origin: "United Arab Emirates", description: "State-of-the-art Dubai precious metals refinery with high-volume industrial capability." },
  { name: "Al Etihad Gold", origin: "United Arab Emirates", description: "Highly respected UAE refinery producing world-class minted gold and silver bullion." },
  { name: "Metalor", origin: "Switzerland", description: "A premier international Swiss group specializing in gold refining and assay services." },
  { name: "Argor-Heraeus", origin: "Switzerland", description: "Globally acclaimed precious metals provider certified by major international exchanges." },
  { name: "Perth Mint", origin: "Australia", description: "Australia's official bullion producer, iconic for official legal tender gold and silver coins." },
  { name: "Royal Canadian Mint", origin: "Canada", description: "Famous for the Maple Leaf series featuring industry-leading anti-counterfeiting laser technology." },
  { name: "Royal Mint", origin: "United Kingdom", description: "The official mint of the UK with over 1,100 years of historic security and design heritage." }
];

export const PRODUCTS: Product[] = [
  // ==========================================
  // --- GOLD BARS (15 Products) ---
  // ==========================================
  {
    id: "gb-1g",
    name_en: "PAMP Suisse 1g Cast Gold Bar",
    name_ar: "سبيكة ذهب بامب سويس ١ جرام",
    category: "gold_bars",
    weight_label: "1 Gram",
    purity: "999.9 Fine Gold",
    manufacturer: "PAMP Suisse",
    country_en: "Switzerland",
    country_ar: "سويسرا",
    availability: "In Stock",
    certificate_en: "Assay Certificate Included",
    certificate_ar: "مرفق بشهادة فحص معتمدة",
    description_en: "A perfect entry point for physical gold investors. This 1g bar features the iconic Lady Fortuna design and comes sealed in a high-security assay card.",
    description_ar: "سبيكة ذهب نقي فئة ١ جرام من مصفاة بامب سويس الشهيرة. تحمل تصميم سيدة الحظ العريق، وتأتي مغلفة ببطاقة أمان وفحص معتمدة لضمان الجودة.",
    technical_specs: { weight_grams: 1, purity: "Au 99.99%", metal: "gold", dimensions: "8.4 mm x 14.7 mm", thickness: "0.5 mm", packaging: "Sealed tamper-proof assay card", serial_number: true },
    image_placeholder: "gold_bar",
    premium_multiplier: 1.15
  },
  {
    id: "gb-2.5g",
    name_en: "Valcambi 2.5g Minted Gold Bar",
    name_ar: "سبيكة ذهب فالكامبي ٢.٥ جرام",
    category: "gold_bars",
    weight_label: "2.5 Grams",
    purity: "999.9 Fine Gold",
    manufacturer: "Valcambi",
    country_en: "Switzerland",
    country_ar: "سويسرا",
    availability: "In Stock",
    certificate_en: "Assay Certificate & Serial",
    certificate_ar: "مرفق بشهادة فحص ورقم تسلسلي فريد",
    description_en: "A small minted gold bar of exquisite Swiss precision. Extremely popular for gifting and incremental wealth accumulation.",
    description_ar: "سبيكة ذهب مصكوكة بدقة سويسرية فائقة ووزن مناسب جداً للهدايا والادخار التدريجي المتنامي.",
    technical_specs: { weight_grams: 2.5, purity: "Au 99.99%", metal: "gold", dimensions: "11.0 mm x 19.0 mm", thickness: "0.7 mm", packaging: "Official secure assay blister", serial_number: true },
    image_placeholder: "gold_bar",
    premium_multiplier: 1.10
  },
  {
    id: "gb-5g",
    name_en: "Valcambi 5g Minted Gold Bar",
    name_ar: "سبيكة ذهب فالكامبي ٥ جرام",
    category: "gold_bars",
    weight_label: "5 Grams",
    purity: "999.9 Fine Gold",
    manufacturer: "Valcambi",
    country_en: "Switzerland",
    country_ar: "سويسرا",
    availability: "In Stock",
    certificate_en: "Assay Certificate & Unique Serial Number",
    certificate_ar: "مرفق بشهادة فحص مع رقم تسلسلي فريد",
    description_en: "Precision crafted by Valcambi, one of Switzerland's most prestigious refineries. Exceptionally polished with crisp edges.",
    description_ar: "سبيكة مصكوكة بدقة عالية من مصفاة فالكامبي السويسرية الشهيرة. تتميز بتشطيب صقيل عاكس وحواف دقيقة.",
    technical_specs: { weight_grams: 5, purity: "Au 99.99%", metal: "gold", dimensions: "14.0 mm x 23.0 mm", thickness: "0.9 mm", packaging: "Auspicious secure assay pack", serial_number: true },
    image_placeholder: "gold_bar",
    premium_multiplier: 1.08
  },
  {
    id: "gb-10g",
    name_en: "Argor-Heraeus 10g Gold Bar",
    name_ar: "سبيكة ذهب أرغور هيريوس ١٠ جرام",
    category: "gold_bars",
    weight_label: "10 Grams",
    purity: "999.9 Fine Gold",
    manufacturer: "Argor-Heraeus",
    country_en: "Switzerland",
    country_ar: "سويسرا",
    availability: "In Stock",
    certificate_en: "Certified Swiss Assay Certificate",
    certificate_ar: "شهادة أصالة سويسرية معتمدة",
    description_en: "This Swiss-made 10g gold bar is recognized globally for liquidity and represents a highly liquid wealth preservation asset.",
    description_ar: "سبيكة ذهب سويسرية وزن ١٠ جرام ممتازة للاستثمار المتوسط. تحظى بقبول عالمي فوري وسيولة تامة بفضل اعتمادها الدولي.",
    technical_specs: { weight_grams: 10, purity: "Au 99.99%", metal: "gold", dimensions: "15.0 mm x 25.4 mm", thickness: "1.6 mm", packaging: "Official Assay blister card", serial_number: true },
    image_placeholder: "gold_bar",
    premium_multiplier: 1.06
  },
  {
    id: "gb-20g",
    name_en: "Emirates Gold 20g Minted Gold Bar",
    name_ar: "سبيكة ذهب إمارات جولد ٢٠ جرام",
    category: "gold_bars",
    weight_label: "20 Grams",
    purity: "999.9 Fine Gold",
    manufacturer: "Emirates Gold",
    country_en: "United Arab Emirates",
    country_ar: "الإمارات العربية المتحدة",
    availability: "In Stock",
    certificate_en: "Official Assay Certificate",
    certificate_ar: "شهادة أصالة رسمية معتمدة",
    description_en: "The iconic UAE refinery bar, depicting the national Rose of Dubai. Represents premium local craftsmanship and high-purity gold assets.",
    description_ar: "سبيكة مصفاة إمارات جولد المتميزة بنقش وردة دبي الوطنية الفاخرة. تمثل تراث الصياغة المحلي الفخم ومطابقة لمعايير دبي الدولية.",
    technical_specs: { weight_grams: 20, purity: "Au 99.99%", metal: "gold", dimensions: "19.0 mm x 31.0 mm", thickness: "1.8 mm", packaging: "Rose of Dubai secure blister card", serial_number: true },
    image_placeholder: "gold_bar",
    premium_multiplier: 1.05
  },
  {
    id: "gb-1oz",
    name_en: "PAMP Suisse 1 oz Minted Gold Bar",
    name_ar: "سبيكة ذهب بامب سويس ١ أونصة",
    category: "gold_bars",
    weight_label: "1 Troy Ounce (31.1g)",
    purity: "999.9 Fine Gold",
    manufacturer: "PAMP Suisse",
    country_en: "Switzerland",
    country_ar: "سويسرا",
    availability: "In Stock",
    certificate_en: "Assay Certificate & Unique Serial Number",
    certificate_ar: "مرفق بشهادة فحص مع رقم تسلسلي فريد",
    description_en: "One of the most globally traded bar sizes, containing exactly 31.1 grams of pure Swiss gold. Perfect balance of cost efficiency and liquidity.",
    description_ar: "أكثر السبائك تداولاً عالمياً بوزن أونصة واحدة كاملة (٣١.١ جرام). تمثل التوازن الأمثل للمحافظ الاستثمارية للتحوط وسهولة البيع والتبادل.",
    technical_specs: { weight_grams: 31.1035, purity: "Au 99.99%", metal: "gold", dimensions: "24.0 mm x 41.0 mm", thickness: "1.7 mm", packaging: "CertiPAMP secure blister pack", serial_number: true },
    image_placeholder: "gold_bar",
    premium_multiplier: 1.045
  },
  {
    id: "gb-50g",
    name_en: "Metalor 50g Cast Gold Bar",
    name_ar: "سبيكة ذهب ميتالور ٥٠ جرام",
    category: "gold_bars",
    weight_label: "50 Grams",
    purity: "999.9 Fine Gold",
    manufacturer: "Metalor",
    country_en: "Switzerland",
    country_ar: "سويسرا",
    availability: "In Stock",
    certificate_en: "Individually Numbered Certificate of Authenticity",
    certificate_ar: "شهادة أصالة مرقمة بشكل فردي",
    description_en: "Metalor Swiss casting delivers timeless, rustic allure. This 50g cast gold bar features a traditional poured finish with unique physical cooling ripples.",
    description_ar: "سبيكة ذهب ميتالور سويسرية مصبوبة يدوياً بأسلوب كلاسيكي فاخر. تتموج السبيكة بتأثيرات تبريد فريدة لتمنحك إحساساً أصيلاً بالسبائك الكلاسيكية الراقية.",
    technical_specs: { weight_grams: 50, purity: "Au 99.99%", metal: "gold", dimensions: "18.5 mm x 32.5 mm", thickness: "4.2 mm", packaging: "Protected velvet pouch & certificate card", serial_number: true },
    image_placeholder: "gold_bar",
    premium_multiplier: 1.04
  },
  {
    id: "gb-100g",
    name_en: "PAMP Suisse 100g Cast Gold Bar",
    name_ar: "سبيكة ذهب بامب سويس ١٠٠ جرام",
    category: "gold_bars",
    weight_label: "100 Grams",
    purity: "999.9 Fine Gold",
    manufacturer: "PAMP Suisse",
    country_en: "Switzerland",
    country_ar: "سويسرا",
    availability: "In Stock",
    certificate_en: "Official PAMP CertiPAMP Packaging & Assayer Stamp",
    certificate_ar: "مغلفة ببطاقة سيرتيبامب الرسمية والختم المعتمد",
    description_en: "A cornerstone for serious physical portfolios. Combining high metal volume with Swiss prestige refining, this 100g cast bar is highly liquid.",
    description_ar: "حجر الأساس للمحافظ الاستثمارية القيمة. تجمع السبيكة بين الوزن المثالي والبريق السويسري الأخاذ لتجعلها السبيكة الأكثر طلباً لسهولة الادخار والنمو.",
    technical_specs: { weight_grams: 100, purity: "Au 99.99%", metal: "gold", dimensions: "24.0 mm x 41.0 mm", thickness: "5.5 mm", packaging: "High-security CertiPAMP hard pack", serial_number: true },
    image_placeholder: "gold_bar",
    premium_multiplier: 1.03
  },
  {
    id: "gb-250g",
    name_en: "Valcambi 250g Cast Gold Bar",
    name_ar: "سبيكة ذهب فالكامبي ٢٥٠ جرام مصبوبة",
    category: "gold_bars",
    weight_label: "250 Grams",
    purity: "999.9 Fine Gold",
    manufacturer: "Valcambi",
    country_en: "Switzerland",
    country_ar: "سويسرا",
    availability: "In Stock",
    certificate_en: "Assayer Certificate Included",
    certificate_ar: "مرفق بشهادة فحص معتمدة من المصفاة",
    description_en: "An impressive asset block representing Swiss purity and standard. The cast finish feels substantial and timeless.",
    description_ar: "أحد أهم الأصول الثمينة لتعزيز الادخار طويل الأجل. صب سويسري رصين يحافظ على قيمتك ويوفر تسعيراً منافساً للغاية.",
    technical_specs: { weight_grams: 250, purity: "Au 99.99%", metal: "gold", dimensions: "35.0 mm x 50.0 mm", thickness: "8.2 mm", packaging: "Acrylic protection sleeve & cert card", serial_number: true },
    image_placeholder: "gold_bar",
    premium_multiplier: 1.025
  },
  {
    id: "gb-10tolas",
    name_en: "Emirates Gold 10 Tolas Gold Bar",
    name_ar: "سبيكة ذهب إمارات جولد ١٠ تولة",
    category: "gold_bars",
    weight_label: "10 Tolas (116.6g)",
    purity: "999.0 Fine Gold",
    manufacturer: "Emirates Gold",
    country_en: "United Arab Emirates",
    country_ar: "الإمارات العربية المتحدة",
    availability: "In Stock",
    certificate_en: "Official Dubai Assay Certification",
    certificate_ar: "شهادة معتمدة من دبي لفحص المعادن الثمينة",
    description_en: "A traditional South Asian unit of weight (1 Tola = 11.66 grams). High liquidity in Middle East and Indian subcontinent precious metal markets.",
    description_ar: "السبيكة الكلاسيكية المفضلة للتداول الإقليمي في الخليج وآسيا. بوزن ١٠ تولات (ما يعادل ١١٦.٦ جرام) من الذهب عيار ٢٤ ونقاوة متميزة.",
    technical_specs: { weight_grams: 116.64, purity: "Au 99.9%", metal: "gold", dimensions: "26.0 mm x 45.0 mm", thickness: "5.2 mm", packaging: "Official Assay blister card", serial_number: true },
    image_placeholder: "gold_bar",
    premium_multiplier: 1.03
  },
  {
    id: "gb-500g",
    name_en: "SAM Precious Metals 500g Cast Gold Bar",
    name_ar: "سبيكة ذهب إس إيه إم ٥٠٠ جرام",
    category: "gold_bars",
    weight_label: "500 Grams",
    purity: "999.9 Fine Gold",
    manufacturer: "SAM Precious Metals",
    country_en: "United Arab Emirates",
    country_ar: "الإمارات العربية المتحدة",
    availability: "Available on Order",
    certificate_en: "Certified standard refiner",
    certificate_ar: "شهادة معتمدة ومطابقة للمواصفات الدولية",
    description_en: "A half-kilogram bar of pure UAE-refined gold. Ideal for high-net-worth vaults looking for tightly-spread gold volume.",
    description_ar: "سبيكة تزن نصف كيلو جرام من الذهب الصافي من مصفاة إس إيه إم بدبي. ممتازة للمستثمرين الباحثين عن اقتناء الذهب بفروقات سعرية ضئيلة.",
    technical_specs: { weight_grams: 500, purity: "Au 99.99%", metal: "gold", dimensions: "40.0 mm x 85.0 mm", thickness: "7.8 mm", packaging: "Padded box with official paper certificates", serial_number: true },
    image_placeholder: "gold_bar",
    premium_multiplier: 1.02
  },
  {
    id: "gb-1kg",
    name_en: "PAMP Suisse 1kg Certified Gold Bar",
    name_ar: "سبيكة ذهب نقي ١ كيلو جرام بامب سويس",
    category: "gold_bars",
    weight_label: "1 Kilogram (1000g)",
    purity: "999.9 Fine Gold",
    manufacturer: "PAMP Suisse",
    country_en: "Switzerland",
    country_ar: "سويسرا",
    availability: "Available on Order",
    certificate_en: "Official Assay Certificate & Hard Box Serialized",
    certificate_ar: "شهادة معتمدة ومحفوظة في علبة فاخرة مرقمة",
    description_en: "The ultimate standard of institutional wealth preservation. Hand-poured in Switzerland, this 1kg bar of pure gold offers the tightest spread and lowest premium.",
    description_ar: "المعيار الأسمى للثروات الكبرى والمؤسساتية وصناديق التحوط الفاخرة. سبيكة مصبوبة بعناية في سويسرا بوزن ١٠٠٠ جرام تضمن لك أفضل أسعار شراء.",
    technical_specs: { weight_grams: 1000, purity: "Au 99.99%", metal: "gold", dimensions: "52.0 mm x 115.0 mm", thickness: "9.0 mm", packaging: "Custom executive box with official paper certificates", serial_number: true },
    image_placeholder: "gold_bar",
    premium_multiplier: 1.015
  },
  {
    id: "gb-etihad-50g",
    name_en: "Al Etihad 50g Minted Gold Bar",
    name_ar: "سبيكة ذهب الاتحاد ٥٠ جرام مصكوكة",
    category: "gold_bars",
    weight_label: "50 Grams",
    purity: "999.9 Fine Gold",
    manufacturer: "Al Etihad Gold",
    country_en: "United Arab Emirates",
    country_ar: "الإمارات العربية المتحدة",
    availability: "In Stock",
    certificate_en: "Assay Certified & Sealed",
    certificate_ar: "شهادة فحص معتمدة ومحكمة الغلق",
    description_en: "Produced by Al Etihad Gold, an accredited refiner in Dubai. Features a modern geometric security background.",
    description_ar: "سبيكة من إنتاج مصفاة الاتحاد للذهب بدبي. تزدان بخلفية هندسية أمنية بالليزر لمكافحة التزوير وضمان حماية السيولة.",
    technical_specs: { weight_grams: 50, purity: "Au 99.99%", metal: "gold", dimensions: "27.0 mm x 47.0 mm", thickness: "2.3 mm", packaging: "Official Etihad tamper-evident packaging", serial_number: true },
    image_placeholder: "gold_bar",
    premium_multiplier: 1.04
  },
  {
    id: "gb-etihad-100g",
    name_en: "Al Etihad 100g Cast Gold Bar",
    name_ar: "سبيكة ذهب الاتحاد ١٠٠ جرام مصبوبة",
    category: "gold_bars",
    weight_label: "100 Grams",
    purity: "999.9 Fine Gold",
    manufacturer: "Al Etihad Gold",
    country_en: "United Arab Emirates",
    country_ar: "الإمارات العربية المتحدة",
    availability: "In Stock",
    certificate_en: "Accredited International Standard Refiner",
    certificate_ar: "مصفاة معتمدة ومطابقة للمعايير الدولية الفاخرة",
    description_en: "Traditional UAE hand-cast bars with raw cooling rings, offering the look of classic treasury gold with contemporary high purity.",
    description_ar: "سبيكة مصبوبة كلاسيكياً من الذهب الصافي من دبي، تبرز جمالية المظهر التقليدي المصبوب بدوائر تبريد مميزة ونقاء استثنائي.",
    technical_specs: { weight_grams: 100, purity: "Au 99.99%", metal: "gold", dimensions: "24.0 mm x 42.0 mm", thickness: "5.0 mm", packaging: "Sealed storage case & paper certificate", serial_number: true },
    image_placeholder: "gold_bar",
    premium_multiplier: 1.03
  },
  {
    id: "gb-emirates-500g",
    name_en: "Emirates Gold 500g Cast Gold Bar",
    name_ar: "سبيكة ذهب إمارات جولد ٥٠٠ جرام",
    category: "gold_bars",
    weight_label: "500 Grams",
    purity: "999.9 Fine Gold",
    manufacturer: "Emirates Gold",
    country_en: "United Arab Emirates",
    country_ar: "الإمارات العربية المتحدة",
    availability: "Available on Order",
    certificate_en: "Official Refinery Assay Certificate",
    certificate_ar: "شهادة معتمدة ومطابقة للمواصفات الرسمية",
    description_en: "The heavyweight choice of local investors. Offers outstanding direct metal premium pricing without complex packaging overhead.",
    description_ar: "الخيار الأقوى للمستثمرين وكبار المدخرين في السوق المحلية. تمنحك قيمة حقيقية للذهب الصافي عيار ٢٤ مع أقل تكلفة تصنيع.",
    technical_specs: { weight_grams: 500, purity: "Au 99.99%", metal: "gold", dimensions: "41.0 mm x 84.0 mm", thickness: "8.0 mm", packaging: "Padded protective case and security sheet", serial_number: true },
    image_placeholder: "gold_bar",
    premium_multiplier: 1.02
  },

  // ==========================================
  // --- SILVER BARS (10 Products) ---
  // ==========================================
  {
    id: "sb-10g",
    name_en: "PAMP Suisse 10g Minted Silver Bar",
    name_ar: "سبيكة فضة بامب سويس ١٠ جرام",
    category: "silver_bars",
    weight_label: "10 Grams",
    purity: "999.0 Fine Silver",
    manufacturer: "PAMP Suisse",
    country_en: "Switzerland",
    country_ar: "سويسرا",
    availability: "In Stock",
    certificate_en: "Assay Sealed Blister card",
    certificate_ar: "مرفق ببطاقة سيرتيبامب المغلقة",
    description_en: "Exquisite Lady Fortuna design minted in fine Swiss silver. Highly liquid pocket wealth asset.",
    description_ar: "سبيكة فضة ناعمة بوزن ١٠ جرام من دار الفحص السويسرية الشهيرة PAMP، تحمل نقش سيدة الحظ الأخاذ.",
    technical_specs: { weight_grams: 10, purity: "Ag 99.9%", metal: "silver", dimensions: "15.0 mm x 25.0 mm", thickness: "1.2 mm", packaging: "CertiPAMP secure blister pack", serial_number: true },
    image_placeholder: "silver_bar",
    premium_multiplier: 1.25
  },
  {
    id: "sb-20g",
    name_en: "Valcambi 20g Minted Silver Bar",
    name_ar: "سبيكة فضة فالكامبي ٢٠ جرام",
    category: "silver_bars",
    weight_label: "20 Grams",
    purity: "999.0 Fine Silver",
    manufacturer: "Valcambi",
    country_en: "Switzerland",
    country_ar: "سويسرا",
    availability: "In Stock",
    certificate_en: "Valcambi Secure Blister Card",
    certificate_ar: "بطاقة فحص وحماية مغلقة من فالكامبي",
    description_en: "Sleek and polished silver bar by Swiss master refiner Valcambi. Perfect for incremental storage.",
    description_ar: "سبيكة فضة سويسرية متميزة بإنهاء فائق اللمعان من مصفاة فالكامبي العريقة بوزن ٢٠ جرام.",
    technical_specs: { weight_grams: 20, purity: "Ag 99.9%", metal: "silver", dimensions: "18.0 mm x 31.0 mm", thickness: "1.5 mm", packaging: "Official serialized blister", serial_number: true },
    image_placeholder: "silver_bar",
    premium_multiplier: 1.20
  },
  {
    id: "sb-1oz",
    name_en: "PAMP Suisse 1 oz Minted Silver Bar",
    name_ar: "سبيكة فضة بامب سويس ١ أونصة",
    category: "silver_bars",
    weight_label: "1 Troy Ounce (31.1g)",
    purity: "999.0 Fine Silver",
    manufacturer: "PAMP Suisse",
    country_en: "Switzerland",
    country_ar: "سويسرا",
    availability: "In Stock",
    certificate_en: "Sealed Assay Blister CertiPAMP",
    certificate_ar: "مرفق ببطاقة سيرتيبامب محكمة الإغلاق",
    description_en: "Featuring the glorious details of the Lady Fortuna icon, this 1oz silver bar reflects light like water on glass, offering absolute Swiss excellence.",
    description_ar: "سبيكة فضة ناعمة بوزن أونصة واحدة تحمل النقش التاريخي لسيدة الحظ. تتألق السبيكة ببريق فضي أخاذ يعكس أرقى معايير الصقل السويسرية.",
    technical_specs: { weight_grams: 31.1035, purity: "Ag 99.9%", metal: "silver", dimensions: "27.0 mm x 47.0 mm", thickness: "2.6 mm", packaging: "CertiPAMP signature security package", serial_number: true },
    image_placeholder: "silver_bar",
    premium_multiplier: 1.15
  },
  {
    id: "sb-50g",
    name_en: "Geiger Edelmetalle 50g Original Silver Bar",
    name_ar: "سبيكة فضة غايغر ٥٠ جرام الأصلية",
    category: "silver_bars",
    weight_label: "50 Grams",
    purity: "999.0 Fine Silver",
    manufacturer: "Geiger Edelmetalle",
    country_en: "Germany",
    country_ar: "ألمانيا",
    availability: "In Stock",
    certificate_en: "German Schloss Guldengossa certified security",
    certificate_ar: "شهادة جودة وميزات أمان من قلعة غولدينغوسا بألمانيا",
    description_en: "Square-shaped luxury silver bars featuring UV glowing security print, textured reverse, and ribbed edges to prevent clipping.",
    description_ar: "سبيكة فضة ألمانية كلاسيكية مربعة الشكل بميزات أمان متقدمة تشمل طلاء للأشعة فوق البنفسجية وحافة مضلعة تمنع التلاعب.",
    technical_specs: { weight_grams: 50, purity: "Ag 99.9%", metal: "silver", dimensions: "32.0 mm x 32.0 mm", thickness: "4.8 mm", packaging: "Security sealed capsule and certificate", serial_number: true },
    image_placeholder: "silver_bar",
    premium_multiplier: 1.15
  },
  {
    id: "sb-100g",
    name_en: "Emirates Gold 100g Silver Bar",
    name_ar: "سبيكة فضة إمارات جولد ١٠٠ جرام",
    category: "silver_bars",
    weight_label: "100 Grams",
    purity: "999.0 Fine Silver",
    manufacturer: "Emirates Gold",
    country_en: "United Arab Emirates",
    country_ar: "الإمارات العربية المتحدة",
    availability: "In Stock",
    certificate_en: "Official Assay certified",
    certificate_ar: "مصحوبة بشهادة نقاوة وفحص معتمدة",
    description_en: "A gorgeous minted silver bar manufactured in Dubai, carrying the Rose of Dubai emblem. A perfect local bullion asset.",
    description_ar: "سبيكة فضة إماراتية رائعة من مصفاة إمارات جولد، تزدان برمز وردة دبي الوطنية لتقديم خيار استثماري إقليمي جذاب.",
    technical_specs: { weight_grams: 100, purity: "Ag 99.9%", metal: "silver", dimensions: "27.0 mm x 47.0 mm", thickness: "8.0 mm", packaging: "Emirates Gold custom blister pack", serial_number: true },
    image_placeholder: "silver_bar",
    premium_multiplier: 1.10
  },
  {
    id: "sb-250g",
    name_en: "Valcambi 250g Minted Silver Bar",
    name_ar: "سبيكة فضة فالكامبي ٢٥٠ جرام مصكوكة",
    category: "silver_bars",
    weight_label: "250 Grams",
    purity: "999.0 Fine Silver",
    manufacturer: "Valcambi",
    country_en: "Switzerland",
    country_ar: "سويسرا",
    availability: "In Stock",
    certificate_en: "Serialized Assay stamp and card",
    certificate_ar: "بطاقة فحص ورقم تسلسلي معتمد من سويسرا",
    description_en: "Excellent medium-weight physical silver asset block from Valcambi. Extremely sharp stamping.",
    description_ar: "سبيكة فضة سويسرية متوسطة الحجم بنقاء ٩٩.٩٪، مصقولة بدقة شديدة مع هوامش سعرية تنافسية.",
    technical_specs: { weight_grams: 250, purity: "Ag 99.9%", metal: "silver", dimensions: "35.0 mm x 50.0 mm", thickness: "14.0 mm", packaging: "Sealed security sleeve and certificate", serial_number: true },
    image_placeholder: "silver_bar",
    premium_multiplier: 1.08
  },
  {
    id: "sb-500g",
    name_en: "SAM Precious Metals 500g Silver Bar",
    name_ar: "سبيكة فضة إس إيه إم ٥٠٠ جرام مصبوبة",
    category: "silver_bars",
    weight_label: "500 Grams",
    purity: "999.0 Fine Silver",
    manufacturer: "SAM Precious Metals",
    country_en: "United Arab Emirates",
    country_ar: "الإمارات العربية المتحدة",
    availability: "In Stock",
    certificate_en: "Accredited UAE Refinery",
    certificate_ar: "مصفاة إماراتية معتمدة دولياً",
    description_en: "Half-kilogram pure silver bar cast in Dubai with a gorgeous cooling finish. Outstanding wholesale hedging.",
    description_ar: "سبيكة فضة مصبوبة يدوياً بوزن نصف كيلو جرام، مصنعة في دبي وتعتبر حلاً رائعاً للحماية المالية واقتناء كميات الفضة الكبرى.",
    technical_specs: { weight_grams: 500, purity: "Ag 99.9%", metal: "silver", dimensions: "40.0 mm x 80.0 mm", thickness: "16.0 mm", packaging: "Vacuum-sealed protection and paper certificate", serial_number: true },
    image_placeholder: "silver_bar",
    premium_multiplier: 1.06
  },
  {
    id: "sb-1kg",
    name_en: "Valcambi 1kg Pure Silver Cast Bar",
    name_ar: "سبيكة فضة فالكامبي ١ كيلو جرام مصبوبة",
    category: "silver_bars",
    weight_label: "1 Kilogram (1000g)",
    purity: "999.0 Fine Silver",
    manufacturer: "Valcambi",
    country_en: "Switzerland",
    country_ar: "سويسرا",
    availability: "In Stock",
    certificate_en: "Serialized Swiss Assayer Stamp & Paper Certificate",
    certificate_ar: "مختومة بختم الفاحص السويسري مع شهادة ورقية رسمية",
    description_en: "High bulk silver storage refined with absolute Swiss purity. Stamped with the iconic Valcambi square logo, this bar is perfect for hedging and robust physical holdings.",
    description_ar: "سبيكة فضة نقية بوزن ١ كيلو جرام لتأمين السيولة في المحفظة. توفر حجماً استثمارياً ممتازاً بهامش سعري ضئيل ومصنعة باعتماد دولي عريق.",
    technical_specs: { weight_grams: 1000, purity: "Ag 99.9%", metal: "silver", dimensions: "52.0 mm x 117.0 mm", thickness: "15.0 mm", packaging: "Vacuum sealed wrap with certificate", serial_number: true },
    image_placeholder: "silver_bar",
    premium_multiplier: 1.05
  },
  {
    id: "sb-100oz",
    name_en: "Royal Canadian Mint 100 oz Silver Cast Bar",
    name_ar: "سبيكة فضة ملكية كندية ١٠0 أونصة مصبوبة",
    category: "silver_bars",
    weight_label: "100 Troy Ounces (3.11kg)",
    purity: "999.9 Fine Silver",
    manufacturer: "Royal Canadian Mint",
    country_en: "Canada",
    country_ar: "كندا",
    availability: "Available on Order",
    certificate_en: "Official Canadian Mint backing",
    certificate_ar: "موثقة ومعتمدة من دار السك الملكية الكندية",
    description_en: "Highly coveted heavyweight bar containing 100oz of pure 99.99% silver. Perfect for standard vaults and hedge allocations.",
    description_ar: "سبيكة فضة عملاقة تزن ٣.١١ كيلو جرام (١٠٠ أونصة تروي) ونقاوة كندية فائقة ٩٩.٩٩٪ من أثمن الأصول الاستثمارية للفضة.",
    technical_specs: { weight_grams: 3110.35, purity: "Ag 99.99%", metal: "silver", dimensions: "72.0 mm x 152.0 mm", thickness: "33.0 mm", packaging: "Hard casing with official stamp and serial", serial_number: true },
    image_placeholder: "silver_bar",
    premium_multiplier: 1.04
  },
  {
    id: "sb-5kg",
    name_en: "Metalor 5kg Cast Silver Bar",
    name_ar: "سبيكة فضة ميتالور ٥ كيلو جرام مصبوبة",
    category: "silver_bars",
    weight_label: "5 Kilograms (5000g)",
    purity: "999.0 Fine Silver",
    manufacturer: "Metalor",
    country_en: "Switzerland",
    country_ar: "سويسرا",
    availability: "Available on Order",
    certificate_en: "Certified International Refiner",
    certificate_ar: "مرفق بشهادة فحص معتمدة دولياً",
    description_en: "Institutional scale silver bar for storage vaults and heavy industrial shielding hedging. Exceptional bulk value.",
    description_ar: "سبيكة ثقيلة للغاية بوزن ٥ كيلو جرام (٥٠٠٠ جرام) للشركات وكبار التجار وصناديق الفضة. تضمن أدنى قيمة تصنيع للجرام الواحد.",
    technical_specs: { weight_grams: 5000, purity: "Ag 99.9%", metal: "silver", dimensions: "90.0 mm x 220.0 mm", thickness: "25.0 mm", packaging: "Sturdy wooden box crate with certificate", serial_number: true },
    image_placeholder: "silver_bar",
    premium_multiplier: 1.03
  },

  // ==========================================
  // --- GOLD COINS (12 Products) ---
  // ==========================================
  {
    id: "gc-sovereign",
    name_en: "Royal Mint Gold Sovereign Coin 7.98g",
    name_ar: "عملة السوفرين الذهبية الملكية ٧.٩٨ جرام",
    category: "gold_coins",
    weight_label: "7.98 Grams (22 Karat)",
    purity: "22 Karat (91.67% Gold, Crown Alloy)",
    manufacturer: "Royal Mint",
    country_en: "United Kingdom",
    country_ar: "المملكة المتحدة",
    availability: "In Stock",
    certificate_en: "Official UK Legal Tender Backed by HM Treasury",
    certificate_ar: "عملة قانونية معتمدة ومدعومة من الخزانة البريطانية",
    description_en: "The historic Sovereign coin, depicting Saint George slaying the dragon. Exceptionally liquid and highly historical.",
    description_ar: "العملة الملكية التاريخية الأشهر في العالم بنقش القديس جورج والتنين. تزن ٧.٩٨ جرام (محتواها الذهبي الصافي هو ٧.٣٢ جرام).",
    technical_specs: { weight_grams: 7.988, purity: "91.67% Au (22k)", metal: "gold", dimensions: "Diameter 22.05 mm", thickness: "1.52 mm", packaging: "Protective acrylic capsule", serial_number: false },
    image_placeholder: "gold_coin",
    premium_multiplier: 1.08
  },
  {
    id: "gc-britannia-1oz",
    name_en: "Royal Mint Britannia 1oz Gold Coin",
    name_ar: "عملة بريتانيا الذهبية دار السك الملكية ١ أونصة",
    category: "gold_coins",
    weight_label: "1 Troy Ounce (31.1g)",
    purity: "999.9 Fine Gold",
    manufacturer: "Royal Mint",
    country_en: "United Kingdom",
    country_ar: "المملكة المتحدة",
    availability: "In Stock",
    certificate_en: "Official Legal Tender Status with Micro-Laser Security",
    certificate_ar: "عملة رسمية قانونية مع ميزة الأمان المجهري بالليزر",
    description_en: "The most secure gold bullion coin in the world. Features four innovative security features including a holographic shifting trident.",
    description_ar: "العملة الذهبية الأكثر أماناً في العالم بفضل تقنيات دار السك البريطانية. تحمل هولوجراماً رائعاً يتغير عند الإمالة لحماية الادخار.",
    technical_specs: { weight_oz: 1, purity: "Au 99.99%", metal: "gold", dimensions: "Diameter 32.69 mm", thickness: "2.8 mm", packaging: "Premium protective acrylic coin capsule", serial_number: false },
    image_placeholder: "gold_coin",
    premium_multiplier: 1.05
  },
  {
    id: "gc-britannia-1/2",
    name_en: "Royal Mint Britannia 1/2oz Gold Coin",
    name_ar: "عملة بريتانيا الذهبية الملكية نصف أونصة",
    category: "gold_coins",
    weight_label: "1/2 Troy Ounce (15.55g)",
    purity: "999.9 Fine Gold",
    manufacturer: "Royal Mint",
    country_en: "United Kingdom",
    country_ar: "المملكة المتحدة",
    availability: "In Stock",
    certificate_en: "Royal Mint Laser Security certified",
    certificate_ar: "شهادة وميزات أمان بالليزر من دار السك البريطانية",
    description_en: "A gorgeous mid-tier weight coin featuring the security-focused micro-engraving of the Royal Mint.",
    description_ar: "عملة بريتانيا فئة نصف أونصة ذهبية ببريق مذهل وخطوط ليزر مجهرية ممتازة للسيولة المرنة.",
    technical_specs: { weight_grams: 15.5517, purity: "Au 99.99%", metal: "gold", dimensions: "Diameter 27.0 mm", thickness: "2.0 mm", packaging: "Protective archival capsule", serial_number: false },
    image_placeholder: "gold_coin",
    premium_multiplier: 1.07
  },
  {
    id: "gc-britannia-1/4",
    name_en: "Royal Mint Britannia 1/4oz Gold Coin",
    name_ar: "عملة بريتانيا الذهبية الملكية ربع أونصة",
    category: "gold_coins",
    weight_label: "1/4 Troy Ounce (7.78g)",
    purity: "999.9 Fine Gold",
    manufacturer: "Royal Mint",
    country_en: "United Kingdom",
    country_ar: "المملكة المتحدة",
    availability: "In Stock",
    certificate_en: "Royal Mint Official Legal Tender",
    certificate_ar: "عملة بريتانيا رسمية قانونية معتمدة للسك والوزن",
    description_en: "Quarter-ounce of high security gold, perfect for fractional gifting and small treasury portfolios.",
    description_ar: "فئة ربع أونصة ذهب صافي عيار ٢٤ ممتازة للتنويع والتبادل السريع برأسمال صغير.",
    technical_specs: { weight_grams: 7.7758, purity: "Au 99.99%", metal: "gold", dimensions: "Diameter 22.0 mm", thickness: "1.63 mm", packaging: "Airtight hard shell capsule", serial_number: false },
    image_placeholder: "gold_coin",
    premium_multiplier: 1.09
  },
  {
    id: "gc-britannia-1/10",
    name_en: "Royal Mint Britannia 1/10oz Gold Coin",
    name_ar: "عملة بريتانيا الذهبية الملكية عشر أونصة",
    category: "gold_coins",
    weight_label: "1/10 Troy Ounce (3.11g)",
    purity: "999.9 Fine Gold",
    manufacturer: "Royal Mint",
    country_en: "United Kingdom",
    country_ar: "المملكة المتحدة",
    availability: "In Stock",
    certificate_en: "Royal Mint Micro-Security Standard",
    certificate_ar: "دار السك الملكية - حماية مجهرية بريتانيا ١/١٠ أونصة",
    description_en: "The smallest standard Britannia coin size. Exceptionally beautiful detail packed into a small golden treasure.",
    description_ar: "أصغر وحدات بريتانيا الذهبية بوزن ٣.١١ جرام. بريق وتفاصيل متناهية الصغر فائقة الدقة والجمال.",
    technical_specs: { weight_grams: 3.1103, purity: "Au 99.99%", metal: "gold", dimensions: "Diameter 16.5 mm", thickness: "1.17 mm", packaging: "Optical collector case", serial_number: false },
    image_placeholder: "gold_coin",
    premium_multiplier: 1.12
  },
  {
    id: "gc-maple-1oz",
    name_en: "Royal Canadian Mint Maple Leaf Gold Coin",
    name_ar: "عملة ورقة القيقب الكندية الذهبية ١ أونصة",
    category: "gold_coins",
    weight_label: "1 Troy Ounce (31.1g)",
    purity: "999.9 Fine Gold",
    manufacturer: "Royal Canadian Mint",
    country_en: "Canada",
    country_ar: "كندا",
    availability: "In Stock",
    certificate_en: "Bullion DNA Anti-Counterfeit Verification Certified",
    certificate_ar: "مسجلة بتقنية التحقق الرقمي من تزييف السبائك DNA",
    description_en: "Made of 99.99% pure Canadian gold, this globally celebrated coin integrates light-diffracting radial lines.",
    description_ar: "مصنوعة من الذهب الكندي فائق النقاوة بنسبة ٩٩.٩٩٪. تنفرد العملة بخطوط قطرية تشتت الضوء وتمنع التزييف تماماً.",
    technical_specs: { weight_oz: 1, purity: "Au 99.99%", metal: "gold", dimensions: "Diameter 30.0 mm", thickness: "2.87 mm", packaging: "High-grade optical archival capsule", serial_number: false },
    image_placeholder: "gold_coin",
    premium_multiplier: 1.05
  },
  {
    id: "gc-maple-1/2",
    name_en: "Royal Canadian Mint Maple Leaf 1/2oz Gold Coin",
    name_ar: "عملة ورقة القيقب الكندية الذهبية نصف أونصة",
    category: "gold_coins",
    weight_label: "1/2 Troy Ounce (15.55g)",
    purity: "999.9 Fine Gold",
    manufacturer: "Royal Canadian Mint",
    country_en: "Canada",
    country_ar: "كندا",
    availability: "In Stock",
    certificate_en: "Royal Canadian Mint DNA certified",
    certificate_ar: "شهادة التحقق الرقمي الكندية DNA لضمان النقاوة",
    description_en: "Highly secure and liquid fractional bullion coin, minted with the exact security standards as the 1oz edition.",
    description_ar: "عملة ورقة القيقب بوزن نصف أونصة (١٥.٥٥ جرام) تقدم نقاء ٩٩٩٩ ومحمية كلياً بالليزر ضد التزييف.",
    technical_specs: { weight_grams: 15.5517, purity: "Au 99.99%", metal: "gold", dimensions: "Diameter 25.0 mm", thickness: "2.23 mm", packaging: "Airtight premium protective case", serial_number: false },
    image_placeholder: "gold_coin",
    premium_multiplier: 1.075
  },
  {
    id: "gc-maple-1/10",
    name_en: "Royal Canadian Mint Maple Leaf 1/10oz Gold Coin",
    name_ar: "عملة ورقة القيقب الكندية الذهبية عشر أونصة",
    category: "gold_coins",
    weight_label: "1/10 Troy Ounce (3.11g)",
    purity: "999.9 Fine Gold",
    manufacturer: "Royal Canadian Mint",
    country_en: "Canada",
    country_ar: "كندا",
    availability: "In Stock",
    certificate_en: "Archival Micro-laser security verified",
    certificate_ar: "موثقة بأمن كندي مجهري فائق النقاوة",
    description_en: "Sought after internationally for micro-hedging and small treasury savings, offering pure 99.99% gold content.",
    description_ar: "أصغر حجم لورقة القيقب الكندية الذهبية بوزن ٣.١١ جرام، توفر الذهب الصافي عيار ٢٤ في قالب فائق الحماية والتداول.",
    technical_specs: { weight_grams: 3.1103, purity: "Au 99.99%", metal: "gold", dimensions: "Diameter 16.0 mm", thickness: "1.22 mm", packaging: "Secure acrylic optical capsule", serial_number: false },
    image_placeholder: "gold_coin",
    premium_multiplier: 1.12
  },
  {
    id: "gc-eagle-1oz",
    name_en: "US Mint American Eagle Gold Coin",
    name_ar: "عملة النسر الأمريكي الذهبية ١ أونصة",
    category: "gold_coins",
    weight_label: "1 Troy Ounce (31.1g)",
    purity: "22 Karat (91.67% Gold, Crown Alloy)",
    manufacturer: "Valcambi",
    country_en: "United States",
    country_ar: "الولايات المتحدة",
    availability: "In Stock",
    certificate_en: "US Treasury Backed Weight & Purity Verification",
    certificate_ar: "موثقة الوزن والنقاوة من الخزانة الأمريكية مباشرة",
    description_en: "A historic classic. The American Eagle is minted in durable Crown Gold (alloyed with silver and copper for scratch resistance) and backed by the US government.",
    description_ar: "العملة الكلاسيكية الأشهر على الإطلاق. تُصك بذهب عيار ٢٢ قيراطاً لزيادة الصلابة ومقاومة الخدوش مع احتواء أونصة واحدة كاملة من الذهب الخالص.",
    technical_specs: { weight_oz: 1, purity: "91.67% Gold (31.1g pure Au)", metal: "gold", dimensions: "Diameter 32.70 mm", thickness: "2.87 mm", packaging: "Airtight hard capsule package", serial_number: false },
    image_placeholder: "gold_coin",
    premium_multiplier: 1.06
  },
  {
    id: "gc-eagle-1/2",
    name_en: "US Mint American Eagle 1/2oz Gold Coin",
    name_ar: "عملة النسر الأمريكي الذهبية نصف أونصة",
    category: "gold_coins",
    weight_label: "1/2 Troy Ounce (15.55g)",
    purity: "22 Karat (Crown Alloy)",
    manufacturer: "Valcambi",
    country_en: "United States",
    country_ar: "الولايات المتحدة",
    availability: "In Stock",
    certificate_en: "Sovereign US Government Backing",
    certificate_ar: "مدعومة بضمان السيادة من الحكومة الأمريكية للوزن",
    description_en: "Features Lady Liberty walking with olive branches and an eagle nesting, struck in hard-wearing alloy.",
    description_ar: "تحمل رمز الحرية الشهير والنسر الأمريكي الرصين. مصنوعة من السبيكة المتينة المقاومة للاحتكاك.",
    technical_specs: { weight_grams: 16.965, purity: "91.67% Gold (15.55g Au content)", metal: "gold", dimensions: "Diameter 27.0 mm", thickness: "2.24 mm", packaging: "Premium optical tight capsule", serial_number: false },
    image_placeholder: "gold_coin",
    premium_multiplier: 1.08
  },
  {
    id: "gc-krugerrand-1oz",
    name_en: "Rand Refinery Krugerrand Gold Coin",
    name_ar: "عملة كروغران الذهبية - جنوب أفريقيا ١ أونصة",
    category: "gold_coins",
    weight_label: "1 Troy Ounce (31.1g)",
    purity: "22 Karat (91.67% Gold, Copper Alloy)",
    manufacturer: "Valcambi",
    country_en: "South Africa",
    country_ar: "جنوب أفريقيا",
    availability: "Limited Stock",
    certificate_en: "The world's first and most widely traded bullion gold coin",
    certificate_ar: "العملة الاستثمارية الأولى تاريخياً والأوسع تداولاً في العالم",
    description_en: "Introduced in 1967. The Krugerrand carries a rich coppery-gold warmth and is recognized instantly by precious metals desks globally.",
    description_ar: "تم إطلاقها لأول مرة عام ١٩٦٧ لتكون الرمز التاريخي لادخار الذهب الخاص. تتميز بلونها الدافئ الجذاب بسبب سبيكة النحاس المتينة.",
    technical_specs: { weight_oz: 1, purity: "91.67% Au (31.1g pure content)", metal: "gold", dimensions: "Diameter 32.77 mm", thickness: "2.83 mm", packaging: "Protective dynamic capsule", serial_number: false },
    image_placeholder: "gold_coin",
    premium_multiplier: 1.055
  },
  {
    id: "gc-philharmonic-1oz",
    name_en: "Austrian Philharmonic 1oz Gold Coin",
    name_ar: "عملة الفيلهارمونية النمساوية الذهبية ١ أونصة",
    category: "gold_coins",
    weight_label: "1 Troy Ounce (31.1g)",
    purity: "999.9 Fine Gold",
    manufacturer: "Valcambi",
    country_en: "Austria",
    country_ar: "النمسا",
    availability: "In Stock",
    certificate_en: "Austrian Mint Official Legal Tender & Purity Certified",
    certificate_ar: "عملة الاتحاد الأوروبي الرسمية القانونية المعتمدة للسك والوزن",
    description_en: "Celebrating the renowned Vienna Philharmonic Orchestra. Struck in pure 24-karat gold, features exquisite musical instruments.",
    description_ar: "تحتفل بفرقة أوركسترا فيينا الفيلهارمونية الشهيرة. مصكوكة بالذهب الخالص عيار ٢٤ ونقوش الآلات الموسيقية الفاخرة.",
    technical_specs: { weight_oz: 1, purity: "Au 99.99%", metal: "gold", dimensions: "Diameter 37.0 mm", thickness: "2.0 mm", packaging: "Austrian Mint premium coin capsule", serial_number: false },
    image_placeholder: "gold_coin",
    premium_multiplier: 1.05
  },

  // ==========================================
  // --- SILVER COINS (11 Products) ---
  // ==========================================
  {
    id: "sc-britannia",
    name_en: "Royal Mint Britannia Silver Coin",
    name_ar: "عملة بريتانيا الفضية - دار السك البريطانية ١ أونصة",
    category: "silver_coins",
    weight_label: "1 Troy Ounce (31.1g)",
    purity: "999.0 Fine Silver",
    manufacturer: "Royal Mint",
    country_en: "United Kingdom",
    country_ar: "المملكة المتحدة",
    availability: "In Stock",
    certificate_en: "Government Backed & High Security Anti-Counterfeit Verification",
    certificate_ar: "موثقة رسمياً وتحتوي على خطوط مجهرية مانعة للتزييف",
    description_en: "Strikingly beautiful and secure, the Britannia 1oz Silver Coin features the iconic figure standing firm amidst wind and waves.",
    description_ar: "إحدى أجمل العملات الفضية العالمية وأكثرها تعقيداً في التصميم. تحمل الرمز الشهير لبريتانيا شامخة أمام أمواج البحر الصاخبة.",
    technical_specs: { weight_oz: 1, purity: "Ag 99.9%", metal: "silver", dimensions: "Diameter 38.61 mm", thickness: "3.0 mm", packaging: "Custom acrylic collector capsule", serial_number: false },
    image_placeholder: "silver_coin",
    premium_multiplier: 1.18
  },
  {
    id: "sc-maple",
    name_en: "Royal Canadian Mint Maple Leaf Silver Coin",
    name_ar: "عملة ورقة القيقب الكندية الفضية ١ أونصة",
    category: "silver_coins",
    weight_label: "1 Troy Ounce (31.1g)",
    purity: "999.9 Fine Silver",
    manufacturer: "Royal Canadian Mint",
    country_en: "Canada",
    country_ar: "كندا",
    availability: "In Stock",
    certificate_en: "Standard 1oz Coin with Royal Bullion DNA technology",
    certificate_ar: "عملة معتمدة نقاوة ٩٩٩٩ مع ميزة الحمض النووي السبيكي DNA",
    description_en: "Boasting unparalleled purity at 99.99% fine silver, the Canadian Silver Maple Leaf is an essential component of physical portfolios.",
    description_ar: "تحظى عملة ورقة القيقب بنقاوة لا تضاهى تصل إلى ٩٩.٩٩٪ من الفضة الخالصة (أربعة تسعات)، وتعتبر خيار الادخار الأقوى عالمياً.",
    technical_specs: { weight_oz: 1, purity: "Ag 99.99%", metal: "silver", dimensions: "Diameter 38.0 mm", thickness: "3.29 mm", packaging: "Archival clear-seal capsule", serial_number: false },
    image_placeholder: "silver_coin",
    premium_multiplier: 1.18
  },
  {
    id: "sc-eagle-1oz",
    name_en: "US Mint American Eagle Silver Coin",
    name_ar: "عملة النسر الأمريكي الفضية ١ أونصة",
    category: "silver_coins",
    weight_label: "1 Troy Ounce (31.1g)",
    purity: "999.0 Fine Silver",
    manufacturer: "Valcambi",
    country_en: "United States",
    country_ar: "الولايات المتحدة",
    availability: "In Stock",
    certificate_en: "Sovereign US Government Guaranteed",
    certificate_ar: "موثقة ومضمونة للوزن والنقاء من حكومة الولايات المتحدة",
    description_en: "The world's most popular silver coin. Struck by the United States Mint, features Adolph A. Weinman's Walking Liberty.",
    description_ar: "العملة الفضية الأكثر مبيعاً وشعبية في العالم. تجسد تصميم الحرية السائرة وتوفر ضماناً تاماً لسهولة التداول وإعادة البيع.",
    technical_specs: { weight_oz: 1, purity: "Ag 99.9%", metal: "silver", dimensions: "Diameter 40.6 mm", thickness: "2.98 mm", packaging: "Protected secure storage capsule", serial_number: false },
    image_placeholder: "silver_coin",
    premium_multiplier: 1.20
  },
  {
    id: "sc-philharmonic-1oz",
    name_en: "Austrian Philharmonic Silver Coin",
    name_ar: "عملة الفيلهارمونية النمساوية الفضية ١ أونصة",
    category: "silver_coins",
    weight_label: "1 Troy Ounce (31.1g)",
    purity: "999.0 Fine Silver",
    manufacturer: "Valcambi",
    country_en: "Austria",
    country_ar: "النمسا",
    availability: "In Stock",
    certificate_en: "Austrian Mint Official Seal",
    certificate_ar: "عملة الفيلهارمونية الرسمية القانونية بختم نمساوي معتمد",
    description_en: "Beautifully minted in Austria, showcasing the Great Organ of the Musikverein and orchestral instruments in pure silver.",
    description_ar: "مصكوكة بفضة نقية بالكامل في النمسا، تظهر الآلات الموسيقية للأوركسترا بأناقة ورونق أوربي كلاسيكي متميز.",
    technical_specs: { weight_oz: 1, purity: "Ag 99.9%", metal: "silver", dimensions: "Diameter 37.0 mm", thickness: "3.2 mm", packaging: "Clear archival coin capsule", serial_number: false },
    image_placeholder: "silver_coin",
    premium_multiplier: 1.18
  },
  {
    id: "sc-krugerrand",
    name_en: "Rand Refinery Krugerrand Silver Coin",
    name_ar: "عملة كروغران الفضية جنوب أفريقيا ١ أونصة",
    category: "silver_coins",
    weight_label: "1 Troy Ounce (31.1g)",
    purity: "999.0 Fine Silver",
    manufacturer: "Valcambi",
    country_en: "South Africa",
    country_ar: "جنوب أفريقيا",
    availability: "In Stock",
    certificate_en: "Rand Refinery Official Bullion Coin",
    certificate_ar: "العملة الفضية الرسمية المعتمدة من دار راند بجنوب أفريقيا",
    description_en: "Bringing the prestige of the legendary Krugerrand series to fine silver. Struck in South Africa.",
    description_ar: "النسخة الفضية من عملة كروغران الأسطورية، لتمنح المستثمرين السيولة والتحوط عيار ٢٤ فضة ناعمة.",
    technical_specs: { weight_oz: 1, purity: "Ag 99.9%", metal: "silver", dimensions: "Diameter 38.7 mm", thickness: "3.0 mm", packaging: "Protective optical capsule", serial_number: false },
    image_placeholder: "silver_coin",
    premium_multiplier: 1.18
  },
  {
    id: "sc-kookaburra",
    name_en: "Perth Mint Kookaburra Silver Coin",
    name_ar: "عملة الكوكابورا الأسترالية الفضية ١ أونصة",
    category: "silver_coins",
    weight_label: "1 Troy Ounce (31.1g)",
    purity: "999.9 Fine Silver",
    manufacturer: "Perth Mint",
    country_en: "Australia",
    country_ar: "أستراليا",
    availability: "Limited Stock",
    certificate_en: "Perth Mint Australian Sovereign Backing",
    certificate_ar: "مضمونة السيادة والسك من مصفاة بيرث الأسترالية الحكومية",
    description_en: "Highly collectible, featuring a annually updated design of the native Australian Kookaburra bird.",
    description_ar: "عملة استثمارية وجامعة للأصول، تتميز بتصميم سنوي متجدد لطائر الكوكابورا الأسترالي بفضة نقاوة أربعة تسعات.",
    technical_specs: { weight_oz: 1, purity: "Ag 99.99%", metal: "silver", dimensions: "Diameter 40.6 mm", thickness: "3.21 mm", packaging: "Official Perth Mint acrylic capsule", serial_number: false },
    image_placeholder: "silver_coin",
    premium_multiplier: 1.22
  },
  {
    id: "sc-koala",
    name_en: "Perth Mint Koala 1oz Silver Coin",
    name_ar: "عملة الكوالا الأسترالية الفضية ١ أونصة",
    category: "silver_coins",
    weight_label: "1 Troy Ounce (31.1g)",
    purity: "999.9 Fine Silver",
    manufacturer: "Perth Mint",
    country_en: "Australia",
    country_ar: "أستراليا",
    availability: "Limited Stock",
    certificate_en: "Perth Mint Official Quality Guarantee",
    certificate_ar: "مصفاة بيرث الأسترالية - عملة الكوالا الفضية الفاخرة",
    description_en: "Featuring the cuddly native Australian Koala. High aesthetic value with low premium volatility.",
    description_ar: "تزدان بصورة حيوان الكوالا الأسترالي المحبوب، دقة نحت عالية وقيمة جمالية فريدة لهواة جمع الفضة.",
    technical_specs: { weight_oz: 1, purity: "Ag 99.99%", metal: "silver", dimensions: "Diameter 40.6 mm", thickness: "4.0 mm", packaging: "Airtight collector capsule", serial_number: false },
    image_placeholder: "silver_coin",
    premium_multiplier: 1.22
  },
  {
    id: "sc-noah",
    name_en: "Geiger Noah's Ark Silver Coin",
    name_ar: "عملة سفينة نوح الفضية أرمينيا ١ أونصة",
    category: "silver_coins",
    weight_label: "1 Troy Ounce (31.1g)",
    purity: "999.0 Fine Silver",
    manufacturer: "Geiger Edelmetalle",
    country_en: "Armenia",
    country_ar: "أرمينيا",
    availability: "In Stock",
    certificate_en: "Geiger Edelmetalle German Quality Certified",
    certificate_ar: "مصكوكة بجودة غايغر الألمانية وتحت رعاية جمهورية أرمينيا",
    description_en: "Depicts Noah's Ark, a dove with an olive branch, and Mount Ararat. Struck beautifully in Leipzig, Germany.",
    description_ar: "تصوير رمزي دقيق لسفينة نوح وجبل أرارات التاريخي وغصن الزيتون، بفضة عالية النقاوة وصك ألماني فاخر.",
    technical_specs: { weight_oz: 1, purity: "Ag 99.9%", metal: "silver", dimensions: "Diameter 38.6 mm", thickness: "2.8 mm", packaging: "Protective coin flip pocket", serial_number: false },
    image_placeholder: "silver_coin",
    premium_multiplier: 1.18
  },
  {
    id: "sc-libertad",
    name_en: "Banco de Mexico Libertad Silver Coin",
    name_ar: "عملة ليبرتاد المكسيكية الفضية ١ أونصة",
    category: "silver_coins",
    weight_label: "1 Troy Ounce (31.1g)",
    purity: "999.0 Fine Silver",
    manufacturer: "Valcambi",
    country_en: "Mexico",
    country_ar: "المكسيك",
    availability: "Limited Stock",
    certificate_en: "Official Mexican Mint Legal Tender",
    certificate_ar: "عملة رسمية قانونية صادرة بمرسوم من بنك المكسيك المركزي",
    description_en: "Features the magnificent Winged Victory statue, standing before the Mexican volcanoes. Extremely low mintage, highly collectible.",
    description_ar: "تحمل نقش تمثال النصر المجنح الأسطوري الشامخ. كمية سك محدودة تجعلها من أكثر العملات طلباً لارتفاع قيمتها الندرة والجمالية.",
    technical_specs: { weight_oz: 1, purity: "Ag 99.9%", metal: "silver", dimensions: "Diameter 40.0 mm", thickness: "2.7 mm", packaging: "High grade optical archival capsule", serial_number: false },
    image_placeholder: "silver_coin",
    premium_multiplier: 1.25
  },
  {
    id: "sc-kangaroo",
    name_en: "Perth Mint Kangaroo Silver Coin",
    name_ar: "عملة الكنغر الأسترالي الفضية ١ أونصة",
    category: "silver_coins",
    weight_label: "1 Troy Ounce (31.1g)",
    purity: "999.9 Fine Silver",
    manufacturer: "Perth Mint",
    country_en: "Australia",
    country_ar: "أستراليا",
    availability: "In Stock",
    certificate_en: "Australian Mint Legal Tender Backed",
    certificate_ar: "عملة الكنغر الأسترالية الفضية مضمونة وموثقة النقاوة",
    description_en: "The standard workhorse bullion coin of Australia. Brilliant micro-radial security lines to deter replication.",
    description_ar: "العملة الاستثمارية الفضية الأساسية في أستراليا. تتميز بخطوط أمان مشتتة للضوء ونقش الكنغر الأسترالي الشهير.",
    technical_specs: { weight_oz: 1, purity: "Ag 99.99%", metal: "silver", dimensions: "Diameter 40.6 mm", thickness: "3.21 mm", packaging: "Airtight hard shell capsule", serial_number: false },
    image_placeholder: "silver_coin",
    premium_multiplier: 1.18
  },
  {
    id: "sc-pandas",
    name_en: "China Mint Panda 30g Silver Coin",
    name_ar: "عملة الباندا الصينية الفضية ٣٠ جرام",
    category: "silver_coins",
    weight_label: "30 Grams",
    purity: "999.0 Fine Silver",
    manufacturer: "Valcambi",
    country_en: "China",
    country_ar: "الصين",
    availability: "Limited Stock",
    certificate_en: "China Mint State Certified Purity",
    certificate_ar: "موثقة الجودة من دار السك الوطنية الصينية للعملات",
    description_en: "Annually updated depiction of pandas in a playful habitat. Struck in a unique modern 30-gram metric standard.",
    description_ar: "تحمل تصميماً متجدداً ومحبوباً لصغار الباندا الصينية. تُصك بنظام متري معاصر وزن ٣٠ جراماً بدلاً من أونصة تروي التقليدية.",
    technical_specs: { weight_grams: 30, purity: "Ag 99.9%", metal: "silver", dimensions: "Diameter 40.0 mm", thickness: "2.98 mm", packaging: "Official China Mint optical capsule", serial_number: false },
    image_placeholder: "silver_coin",
    premium_multiplier: 1.25
  }
];

export const WHY_US_ITEMS = [
  {
    title_en: "International Institutional Compliance",
    title_ar: "امتثال مؤسسي بمعايير دولية",
    desc_en: "Operating in the heart of Dubai, the absolute global epicentre of precious metals trading, with strict international standards of compliance.",
    desc_ar: "نعمل من قلب دبي، العاصمة العالمية لتداول الذهب والمعادن الثمينة، بامتثال تام للأنظمة المرعية والاعتمادات الدولية."
  },
  {
    title_en: "Wholesale Global Solutions",
    title_ar: "حلول تداول بالجملة وعالمية",
    desc_en: "We offer tailored, highly competitive direct pricing for institutional bullion procurement, private funds, high-volume trading, and institutional reserves.",
    desc_ar: "نقدم تسعيراً مباشراً وتنافسياً مخصصاً لعمليات شراء السبائك الكبرى للمؤسسات، الصناديق الخاصة، تداول الكميات الضخمة، والاحتياطيات المؤسسية."
  },
  {
    title_en: "Secure Global Vaulting",
    title_ar: "تخزين وشحن عالمي آمن",
    desc_en: "Fully covered door-to-door transit via high-security logistics (Brink's / Transguard) with direct storage options in UAE premium, certified vaults.",
    desc_ar: "شحن مغطى بالكامل من الباب إلى الباب عبر كبرى شركات الأمن (برينكس / ترانسجارد) مع خيارات تخزين مباشر في أرقى الخزائن المؤمنة والمعتمدة في دبي."
  },
  {
    title_en: "Absolute Pricing Transparency",
    title_ar: "شفافية مطلقة في التسعير",
    desc_en: "PGR UAE is founded on absolute transparency. Our digital rates align directly with global gold/silver spot tickers with zero hidden broker premiums.",
    desc_ar: "تأسست بي جي آر على مبدأ الشفافية الكاملة. أسعارنا الرقمية تتبع شاشات التداول العالمية مباشرة بدون أي رسوم وساطة خفية."
  }
];
